# Generated by Django 2.1.15 on 2020-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatInfo',
            fields=[
                ('platform', models.CharField(blank=True, db_column='Platform', max_length=50, null=True)),
                ('sn', models.CharField(db_column='SN', max_length=11, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=20, null=True)),
                ('currenttask', models.TextField(blank=True, db_column='CurrentTask', null=True)),
                ('os', models.CharField(blank=True, db_column='OS', max_length=30, null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=30, null=True)),
                ('bios', models.CharField(blank=True, db_column='BIOS', max_length=30, null=True)),
                ('wlan_module', models.TextField(blank=True, db_column='WLAN Module', null=True)),
                ('wlan_driver', models.TextField(blank=True, db_column='WLAN Driver', null=True)),
                ('bt_module', models.TextField(blank=True, db_column='BT Module', null=True)),
                ('bt_driver', models.TextField(blank=True, db_column='BT Driver', null=True)),
                ('wwan_module', models.TextField(blank=True, db_column='WWAN Module', null=True)),
                ('wwan_driver', models.TextField(blank=True, db_column='WWAN Driver', null=True)),
                ('gnss_module', models.TextField(blank=True, db_column='GNSS Module', null=True)),
                ('gnss_driver', models.TextField(blank=True, db_column='GNSS Driver', null=True)),
                ('nic_module', models.TextField(blank=True, db_column='NIC Module', null=True)),
                ('nic_driver', models.TextField(blank=True, db_column='NIC Driver', null=True)),
                ('nfc_module', models.TextField(blank=True, db_column='NFC Module', null=True)),
                ('nfc_driver', models.TextField(blank=True, db_column='NFC Driver', null=True)),
                ('rfid_module', models.TextField(blank=True, db_column='RFID Module', null=True)),
                ('rfid_driver', models.TextField(blank=True, db_column='RFID Driver', null=True)),
                ('lastusedtime', models.DateTimeField(blank=True, db_column='LastUsedTime', null=True)),
                ('tag', models.CharField(blank=True, db_column='Tag', max_length=50, null=True)),
                ('wwan_firmware', models.TextField(blank=True, db_column='WWAN Firmware', null=True)),
                ('wwan_modem', models.TextField(blank=True, db_column='WWAN Modem', null=True)),
            ],
            options={
                'db_table': 'cat_info',
                'managed': False,
            },
        ),
    ]
