# Generated by Django 2.1.15 on 2020-03-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasktable',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sn', models.CharField(db_column='SN', max_length=11)),
                ('task', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, db_column='startTime', null=True)),
                ('finishtime', models.DateTimeField(blank=True, db_column='finishTime', null=True)),
                ('series', models.TextField(blank=True, null=True)),
                ('local_id', models.IntegerField(blank=True, null=True)),
                ('result_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taskTable',
            },
        ),
    ]
